[package]
name = "unwind-sys"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
links = "unwind"

[features]
ptrace = []

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
