[package]
name = "rstack"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[dependencies]
unwind-sys = { path = "unwind-sys" }

[workspace]
members = [
    "systest",
    "unwind",
    "unwind-sys",
]
