[package]
name = "unwind"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[features]
ptrace = ["unwind-sys/ptrace"]

[dependencies]
libc = "0.2"
foreign-types = "0.3"

unwind-sys = { path = "../unwind-sys", features = ["native"] }
