version: 2.1

jobs:
  test:
    parameters:
      image: string
    docker:
      - image: << parameters.image >>
    environment:
      RUSTFLAGS: -D warnings
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y libunwind-dev libdw-dev
      - restore_cache:
          key: registry
      - run: cargo generate-lockfile
      - save_cache:
          key: registry-{{ .BuildNum }}
          paths:
            - /usr/local/cargo/registry/index
      - restore_cache:
          key: deps-<< parameters.image >>-{{ checksum "Cargo.lock" }}
      - run: cargo test
      - run: cargo test --manifest-path unwind/Cargo.toml --all-features
      - run: cargo run --manifest-path unwind-systest/Cargo.toml --all-features
      - run: cargo run --manifest-path dw-systest/Cargo.toml --all-features
      - save_cache:
          key: deps-<< parameters.image >>-{{ checksum "Cargo.lock" }}
          paths:
            - target
            - /usr/local/cargo/registry/cache

workflows:
  version: 2
  test:
    jobs:
      - test:
          image: rust:1.30.0
      - test:
          image: rustlang/rust:nightly
