[package]
name = "systest"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[features]
native = ["unwind-sys/native"]
ptrace = ["unwind-sys/ptrace"]

[dependencies]
unwind-sys = { path = "../unwind-sys" }
libc = "0.2"

[build-dependencies]
ctest = "0.1"
