name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  build:
    name: ${{ matrix.target }} ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64
          - i686
          - aarch64
        version:
          # - 1.2.1
          - 1.4.0
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          case ${{ matrix.target }} in
            aarch64)
              version=nightly
              ;;
            *)
              version=1.38.0
              ;;
          esac

          rustup update $version
          rustup default $version
          rustup target add ${{ matrix.target }}-unknown-linux-gnu
      - name: Install cross compiler
        run: |
          case ${{ matrix.target }} in
            x86_64)
              exit 0
              ;;
            i686)
              packages=gcc-multilib
              ;;
            aarch64)
              packages="gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user"
              ;;
          esac

          apt-get update
          apt-get install -y $packages
      - name: Build libunwind
        run: |
          case ${{ matrix.target }} in
            x86_64)
              args=
              ;;
            i686)
              args=CFLAGS=-m32
              ;;
            aarch64)
              args="CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++"
          esac

          curl -L https://download.savannah.nongnu.org/releases/libunwind/libunwind-${{ matrix.version }}.tar.gz | tar -C /tmp -xf -
          cd /tmp/libunwind-${{ matrix.version }}
          ./configure --disable-static --host ${{ matrix.target }}-linux-gnu --target ${{ matrix.target }}-linux-gnu --prefix=/opt/libunwind $args
          make -j$(nproc)
          make install