name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  libunwind:
    strategy:
      matrix:
        target:
          - x86_64
          - i686
          - aarch64
        version:
          - 1.2.1
          - 1.4.0
    name: libunwind ${{ matrix.target }} ${{ matrix.version }}
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_ALLOW_CROSS: 1
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER: qemu-aarch64 -L /usr/aarch64-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: |
          case ${{ matrix.target }} in
            aarch64)
              version=nightly
              ;;
            *)
              version=1.44.0
              ;;
          esac

          rustup update $version
          rustup default $version
          rustup target add ${{ matrix.target }}-unknown-linux-gnu
      - name: Install cross compiler
        run: |
          case ${{ matrix.target }} in
            x86_64)
              exit 0
              ;;
            i686)
              packages=gcc-multilib
              ;;
            aarch64)
              packages="gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user"
              ;;
          esac

          sudo apt-get update
          sudo apt-get install -y $packages
      - name: Libunwind cache
        id: libunwind-cache
        uses: actions/cache@v2
        with:
          path: ~/libunwind
          key: libunwind-${{ matrix.version }}-${{ matrix.target }}
      - name: Build libunwind
        if: ${{ !steps.libunwind-cache.outputs.cache-hit }}
        run: |
          case ${{ matrix.target }} in
            x86_64)
              args=
              ;;
            i686)
              args=CFLAGS=-m32
              ;;
            aarch64)
              args="CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++"
          esac

          curl -L https://download.savannah.nongnu.org/releases/libunwind/libunwind-${{ matrix.version }}.tar.gz | tar -C /tmp -xzf -
          cd /tmp/libunwind-${{ matrix.version }}
          ./configure --disable-static --host ${{ matrix.target }}-linux-gnu --target ${{ matrix.target }}-linux-gnu --prefix=$HOME/libunwind $args
          make -j$(nproc)
          make install
      - name: Setup eenvironment variables
        run: |
          echo "PKG_CONFIG_PATH=$HOME/libunwind/lib/pkgconfig" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$HOME/libunwind/lib" >> $GITHUB_ENV
      - name: Systest
        run: cargo run --manifest-path unwind-systest/Cargo.toml --target ${{ matrix.target }}-unknown-linux-gnu
      - name: Unwind test
        run: cargo test --manifest-path unwind/Cargo.toml --target ${{ matrix.target }}-unknown-linux-gnu